config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :video, only: [:index, :show] do
	resources :analyze
end

get '/duration' => 'video#duration'
post 'acknowledge' => 'video#acknowledge'

get '/getStarted' => 'video#getStarted'
get '/explore' => 'video#explore'
get '/analyze' => 'analyze#index'

root 'video#index'
end

app/models/analyze.rb
class Analyze < ApplicationRecord
	mount_uploader :file_location, DataUploader 
	belongs_to :video
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
	has_many :analyzes
end

app/controllers/analyze_controller.rb
class AnalyzeController < ApplicationController

	def index
		@video = Video.all
	end

	def create
		begin
			@video = Video.find(params[:video_id])
			@analyze = @video.analyzes.create(params[:analyze].permit(:file_location))
			redirect_to video_analyze_path(@video,@analyze)
		rescue => error
			redirect_to @video
		end
	end

	def show	
		@analyze = Analyze.find(params[:id])
		`python ./public/scripts/plot.py ./public#{@analyze.file_location.url} ./public/data/#{@analyze[:video_id]}/data.txt #{@analyze[:video_id]}`
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/video_controller.rb
class VideoController < ApplicationController
	
	protect_from_forgery with: :null_session

	def getStarted
	end

	def explore
		@videos = Video.all
	end

	def index
	end

	def new
		@video = Video.new
	end

	def show
		@video = Video.find(params[:id])
	end

	def duration
		if Video.exists?(:id => params[:id].to_i)
			@video = Video.find(params[:id].to_i)
			response = @video[:duration].to_s+","+@video[:title].to_s
			render plain: response
		else
			render plain: "-1,-1"
		end
	end

end

app/helpers/analyze_helper.rb
module AnalyzeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/analyze/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="/getStarted">Smart Learning System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href= "/getStarted"><b>Get Started<b></a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href= "/explore"><b>Explore<b></a>
            </li>
           </ul>
        </div>
      </div>
</nav>

<header class="bg-warning text-white">
      <div class="container text-center">
        <h1>Analyze all the attention graphs</h1>
      </div>
</header>

<% @video.each do |a|%>
<div class = "row">
  <div class = "col-md-3">
  </div>
  <%= a.id %>
  <%= image_tag("/images/#{a.id}dualplot.png") %>
</div>
<% end %>

app/views/analyze/show.html.erb
<div class = "row">
	<div class = "col-md-3">
	</div>
	<%= image_tag("/images/#{@analyze[:video_id]}plot.png") %>
</div>
<div class = "row">
	<div class = "col-md-3">
	</div>
	<%= image_tag("/images/#{@analyze[:video_id]}dualplot.png") %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eeg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Megrim' rel='stylesheet'>
    <% if !notice.nil? || !alert.nil? %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/video/explore.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="/getStarted">Smart Learning System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href= "/getStarted"><b>Get Started<b></a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href= "/analyze"><b>Analysis<b></a>
            </li>
           </ul>
        </div>
      </div>
</nav>

<header class="bg-warning text-white">
      <div class="container text-center">
        <h1>Courses</h1>
      </div>
</header>

<br/>
<div class = "container">
	<div class = "row">
		<% @videos.each do |v| %>
			<div class="card border-success mb-3" style="width: 18rem; margin:0 auto">
			  <div class="card-body">
			    <h5 class="card-title"> <%= v.title %> </h5>
			    <p class="card-text">Demo Video</p>
			    <button class = "btn btn-success">
			    	<%= link_to "Watch", video_path(v), :class => "btn-md" %>
			    </button>
			  </div>
			</div>
		<% end %>
	</div>
</div>

app/views/video/getStarted.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Smart Learning System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#about"><b>About</b></a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services"><b>How to use</b></a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#explore"><b>Explore</b></a>
            </li>
           </ul>
        </div>
      </div>
    </nav>

    <header class="bg-warning text-white">
      <div class="container text-center">
        <h1>Get Started</h1>
      </div>
    </header>

    <div id = "purple">
      <section id="about">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 mx-auto">
              <h2>About</h2>
              <p class="lead">The Smart Learning System uses the data collected from your EEG device to give you better analysis on your online learning. It gets the following things done for you:</p>
              <ul>
                <li>Give you chart of your attention levels during the course.</li>
                <li>Provide you deeper analytics of your learning based on the data from your peers.</li>
                <li>Proving you real-time feedback.</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      <section id="services" class="bg-light">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 mx-auto">
              <h2>How to use</h2>
              <p class="lead">Follow the steps to use the Smart Learning System.</p>
              <ul>
                <li> Connect your EEG device.</li>
                <li> Open the video you want to watch, copy down its ID and pass it on the desktop app.</li>
                <li> Once done press stop and upload the data.</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      <section id="explore">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 mx-auto">
              <h2>Explore</h2>
              <p class="lead">Choose from the courses available</p>
              <p>
                <button class = "btn btn-danger btn-sm">
                  <%= link_to "Courses", explore_path, :class => "btn-sm" %>
                </button>
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>

app/views/video/index.html.erb
<canvas id="canvas"></canvas>

<div id = "front-text">
	<h1><p>Using EEG</br> 
	to improve your online</br>learning Experience </p></h1>
</div>

<h3>
    <div class = "btn btn-danger">
        <%=link_to "Get Started", getStarted_path, :class => "btn" %>
    </div>
</h3>

app/views/video/show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="/getStarted">Smart Learning System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/explore"><b>Courses<b></a>
            </li>
           </ul>
        </div>
      </div>
</nav>

<div id = "video">
	<%= video_tag "#{@video.location}", controls: true, size: "800x500", skip_pipeline: true %>
</div>
<div id = "video-title">
  <h2><%= "Video title - #{@video.title} (id-#{@video.id})" %></h2>
</div> 

<div id = "upload">
<%= simple_form_for [@video, @video.analyzes.build], url: video_analyze_index_path(@video) do |f| %>
  <%= f.file_field :file_location %>
  <%= f.button :submit %>
<% end %>
</div>